### PR TITLE
Render CSS as an ERB partial instead of fetching from server

### PR DESCRIPTION
**Pull request by mauro-oto**
Rails 5 has a problem with this gem, mentioned here: https://github.com/ono/resque-cleaner/issues/42. This PR makes it so that the CSS is served inline in the HTML, rendered as a partial.

Please check it out, thanks!

### CODE REVIEW

**Comment by garettarrowood** [comment]
+1   Would love to see this fix get merged.

**Comment by wadewinningham** [comment]
+1

**Comment by mauro-oto** [comment]
@ono could we get this merged? We're getting many exceptions because of this on a Rails 5 project. Thanks for your work on this gem!

**Comment by ono** [comment]
Cool. I haven't used Rails or Resque for while so haven't tried this change by myself. But it seems to be a fair bug change so will merge and bump the version. Thanks :+1:

**Comment by ono** [comment]
https://rubygems.org/gems/resque-cleaner/versions/0.4.0

**Pull request merged**
