### PR TITLE
fix regex filter for cleaner_exec - closes refs #36

### PR DESCRIPTION
**Pull request by staszek-arsdata**
fix for issue #36

### CODE REVIEW

**Comment by ono** [comment]
Good work! Could you remove https://github.com/staszek-arsdata/resque-cleaner/commit/49925c9aaaabedd1733671b629fbd786d853bd86 from the pull request? I will look after the version bump.

**Comment by staszek-arsdata** [comment]
Thanks. I was having problems with bundler updating the gem in my project, so I added version bump, after pull request.  Looks like this commit has been added to pull request too. I'm new to github. Commit removed. Is it OK now?

**Comment by ono** [comment]
great :+1: will merge and do version bumping soon. thanks a lot!

**Comment by staszek-arsdata** [comment]
Great! Thanks for awesome resque plugin!

**Comment by ono** [comment]
@staszek-arsdata merged, version bumped and pushed to ruby gem: https://rubygems.org/gems/resque-cleaner

thanks again for contributing!

**Pull request merged**
